title: ubuntu-dev-setup
description: Enterprise-grade solution with dark neon theme
url: "https://tiaastor.github.io"
baseurl: "/ubuntu-dev-setup"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author: Tiation
github_username: tiaastor
